# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treated', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=120)),
                ('medical_issue', models.CharField(max_length=200)),
                ('issue_type', models.CharField(choices=[('EG', 'Emergency'), ('RG', 'Regular')], max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.UserDetail')),
            ],
        ),
    ]
