# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('medical_issue', models.CharField(max_length=200)),
                ('issue_type', models.CharField(choices=[('EG', 'Emergency'), ('RG', 'Regular')], max_length=120)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
