# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='username',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
