# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sos_detail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_register.UserDetail'),
        ),
    ]
