# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 07:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobileNumber', models.IntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid Mobile Number', message='Mobile Number should of 10 Digits', regex='^\\d{10}$')])),
                ('avatar', models.ImageField(default='/static/UserProfile/defaultProfileImage.png', upload_to='UserProfileImages/')),
            ],
        ),
    ]
