# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('mobile_number', models.IntegerField()),
                ('blood', models.CharField(default='A+', max_length=12)),
            ],
        ),
    ]
