# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobileNumber', models.IntegerField(default=0)),
                ('avatar', models.ImageField(default='/static/UserProfile/defaultProfileImage.png', upload_to=login_register.models.get_upload_url)),
            ],
        ),
    ]
