# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
