# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(default='shreyanshss7@gmail.com', max_length=254),
        ),
    ]
