# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_auto_20170925_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobileNumber',
            field=models.IntegerField(default=0),
        ),
    ]
