# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_userdetail_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
    ]
