# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import login_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20170925_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/UserProfile/defaultProfileImage.png', upload_to=login_register.models.get_upload_url),
        ),
    ]
