# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login_register.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20170925_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='/static/UserProfile/defaultProfileImage.png', upload_to=login_register.models.get_upload_url),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
