# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20171001_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='blood',
            field=models.CharField(default='A+', max_length=12),
        ),
    ]
